serviceA:
  repo: https://gituhub.com/petar-cvit/argocd.applictionset
  colors:
    - red
    - green
    - blue
serviceB:
  repo: https://github.com/petar-cvit/argocd.applictionset
  colors:
    - red
    - yellow
