apiVersion: apps/v1
kind: Deployment
metadata:
  name: anton-green
  namespace: lala
spec:
  replicas: 1
  selector:
    matchLabels:
      app: anton
  template:
    metadata:
      name: anton-green
      namespace: lala
    spec:
      containers:
        - env:
            - name: KEY
              value: im.service.b
            - name: COLOR
              value: green
            - name: TENANCY
              value: tenancy/green
            - name: COMPLEMENT
              value: red
          image: image:v123
          name: anton-green
---
apiVersion: v1
kind: Service
metadata:
  name: anton-green
  namespace: lala
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: anton
