libVersion: v1.0.3
services:
  service-d:
    version: v2.3.4
    isColorful: true
  service-e:
    version: v1.3.2
    colors:
      - orange
      - purple
      - grey
  multitenancy-service:
    version: v0.0.1
    isColorful: false