apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/instance: colors-service
  name: first-service
  namespace: demo
spec:
  generators:
    - list:
        elements:
          - color
  template:
    metadata:
      name: first-service-green
    spec:
      destination:
        namespace: demo
        server: https://kubernetes.default.svc
      project: default
      source:
        path: synth/services/demo/first-service
        repoURL: https://github.com/petar-cvit/argocd.applicationset
        targetRevision: HEAD
