apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/instance: colors-service
  name: service-c
  namespace: namespace-b
spec:
  generators:
    - list:
        elements:
          - color
  template:
    metadata:
      name: service-c-green
    spec:
      destination:
        namespace: namespace-b
        server: https://kubernetes.default.svc
      project: default
      source:
        path: synth/services/namespace-b/service-c
        repoURL: https://github.com/petar-cvit/argocd.applicationset
        targetRevision: HEAD
