apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  generators:
    - list:
        elements:
          - color: green
          - color: blue
          - color: red
  template:
    metadata:
      name: 'my-service-{{color}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/petar-cvit/argocd.applicationset
        targetRevision: HEAD
        path: applications
        plugin:
          name: dpl-plugin
          env:
            - name: color
              value: '{{color}}'
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: guestbook
