{{- range $k, $v := .Values.services }}
{{ if ne $k "namespace" }}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/instance: colors-service
  name: {{ $k }}-app
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          {{- if $v.isColorful }}
          {{- range $color := $.Values.colors }}
          - color: {{$color}}
          {{- end }}
          {{- else }}
          {{- range $color := $v.colors }}
          - color: {{$color}}
          {{- end }}
          {{- end }}
  template:
    metadata:
      name: {{ $k }}-{{"{{color}}"}}
    spec:
      destination:
        namespace: guestbook
        server: 'https://kubernetes.default.svc'
      project: default
      source:
        path: lib
        repoURL: 'https://github.com/petar-cvit/argocd.applicationset'
        targetRevision: HEAD
        plugin:
          name: cdk8s-service
          env:
            - name: NAME
              value: {{ $k }}
            - name: NAMESPACE
              value: {{ $.Values.namespace }}
            - name: VERSION
              value: {{ $v.version }}
            - name: COLOR
              value: '{{"{{color}}"}}'
---
{{end}}
{{- end }}