apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/instance: colors-service
  name: anton
  namespace: lala
spec:
  generators:
    - list:
        elements:
          - color
  template:
    metadata:
      name: anton-green
    spec:
      destination:
        namespace: lala
        server: https://kubernetes.default.svc
      project: default
      source:
        path: synth/services/lala/anton
        repoURL: https://github.com/petar-cvit/argocd.applicationset
        targetRevision: HEAD
