apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  labels:
    app.kubernetes.io/instance: colors-service
  name: demo-service
  namespace: new-ns
spec:
  generators:
    - list:
        elements:
          - color
  template:
    metadata:
      name: demo-service-green
    spec:
      destination:
        namespace: new-ns
        server: https://kubernetes.default.svc
      project: default
      source:
        path: synth/services/new-ns/demo-service
        repoURL: https://github.com/petar-cvit/argocd.applicationset
        targetRevision: HEAD
