apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-b-blue
  namespace: namespace-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service-b
  template:
    metadata:
      name: service-b-blue
      namespace: namespace-a
    spec:
      containers:
        - env:
            - name: KEY
              value: im.service.b
            - name: COLOR
              value: blue
            - name: TENANCY
              value: tenancy/blue
            - name: COMPLEMENT
              value: orange
          image: image:v123
          name: service-b-blue
---
apiVersion: v1
kind: Service
metadata:
  name: service-b-blue
  namespace: namespace-a
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: service-b
