name: Test

on:
  push:
    paths:
      - 'config/**'

jobs:
  commit-synth-manifest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
      - name: Install cdk8s
        run: npm install -g cdk8s-cli
      - uses: jitterbit/get-changed-files@v1
        id: abc
        with:
          format: space-delimited
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Printing
        env:
          GH_DEMO_APPSETS_TOKEN: ${{ secrets.GH_DEMO_APPSETS_TOKEN }}
        run: |
          for i in ${{ steps.abc.outputs.all }}; do
            if [[ $i =~ config/(prod|stage)/([a-z|-]*).yaml ]]; then
              echo "working $i"
              echo "env ${BASH_REMATCH[1]}"
              echo "ns ${BASH_REMATCH[2]}"
              echo $(cat $i | yq .libVersion)
              
              docker pull petarcvit223/namespaces:v2.4
              docker run petarcvit223/namespaces:v2.4 ./bin/namespaces ${BASH_REMATCH[1]} ${BASH_REMATCH[2]} $GH_DEMO_APPSETS_TOKEN
            else
              echo "skip $i"
            fi
          done
